### ISSUE TITLE
Job Poster Builder: Step 02 - Job Information

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#862]
# Description
In this step, the hiring manager will provide basic job information like Job Title, Term, Classification, Level, Security Level, Language Profile, Location and are Remote Work, Telework and Flexible Hours allowed. After this step is complete we also show an encouraging render of some of the data.

As we add inputs to this UI, we will be removing the corresponding ones from the old UI that admins are still using (/en/manager/jobs/##/edit).

- [x] This task requires a unit test.

**Acceptance Criteria**
***Page & Nav***
- [ ] Depending on the button pressed on Step 0 (#942), we should either be on the /en version of the page or on the /fr version.
- [ ] If we are on the /en version of the page, all the "translatable" fields (like job title) should only be showing the English Input (and French only for /fr). This means you will need to toggle between the language of the page if you ever want to complete both languages.
- [ ] This page is the second on the progress tracker (top right) and should follow the same logic as described in #942

***Form***
- [ ] Job Title is the input for the EN or FR job title based on the language of the page you're on. This input should be removed from the old form (as all inputs we're moving to this form should be).
- [ ] "How long is the term (in months)" corresponds to Position Duration in the Timetable section of the old form.

Classification and Level are NEW. Previously this was a single text input with some regex restrictions. Now they have separate dropdowns.
- [ ] "What is the classification" should ideally get saved to the old text field we had for Classification. That will help us maintain backwards compatibility with older job posters.
- [ ] Classification should be removed from the old form.
- [ ] "What is the level" should be saved to a new integer field
- [ ] The Level pull-down is simply a list from 1 - 9
- [ ] The job poster needs to get updated to display this information correctly. It should display "Classification"-"Level". For example CS-04 or ENsur-05.

- [ ] "What is the Security Level?" replaces "Security Clearance" from the old form
- [ ] "What is the language profile" replaces "Language Requirement" from the old form.
- [ ] The text for "language profile" we want to display for managers is different then the text to display to candidates. Please see content doc for how they should appear here.
- [ ] Only NOC code should remain under "classifications" in the old form.

***Remote Work***
- [ ] As in the mock-up there is some added text below the input label.
- [ ] Remote work now has several options. On the old form it was just a checkbox. This new input should replace the old one.
- [ ] To keep thing simple, let's just map the two new "Yes" options to true and the "No" option to false. That way we don't need to make changes to the job poster. We have created an issue for the improved version (#949) but it is not prioritized for now.

***Telework and Flexible Hours***
These fields currently exist on the Manager Profile "/en/manager/profile/##/edit". 
- [ ] As in the mock-up there is some added text below the input label.
- [ ] Create new fields on the job poster model to capture this data (Gray is reaching beyond his level of expertise here, please confirm with other devs if needed)
- [ ] Removing these fields from the manager profile will be tricky. Ideally we copy the current values in every manager's profile over to the new fields of all their job posters. But feel free to propose other solutions.

***Validation***
- [ ] All fields are required.

**Job Poster Card**
When the Next button is clicked, the next page shows the Job Card with some encouraging text. The Job Poster Card will display the following details pulled from the previous two pages;

- [ ] Job title 
- [ ] Department
- [ ] Location
- [ ] Duration or Term (in months)
- [ ] Is Remote Work Allowed (Yes or No)

- [ ] Additional information such as Average Annual Salary, Apply by and Applicants to Date will be posted on the preview but will be static only content.

Functionality on the Job Poster Card will include;
- [ ] a link back to previous screen so that users can make changes, 
- [ ] a save or continue button to move to the next step,
- [ ] a rollover on the 'View Job' button informing users that 'There's nothing to view yet but, we're off to a good start'.

**Link to Wireframe(s):**
[Job Details and Preview](https://xd.adobe.com/view/19e2b905-9ef3-4ba3-44b7-b5317334e680-6fd3/)

1. Click each pull-down menu to see available options. 
2. Click next a couple times to get to the Job Card

**Link to Content:**
[Job Details and Preview](https://docs.google.com/document/d/1hoHWlctAIVbFHmyzBmnGyaRjvkBIcvYkMxSVzmiLm2Q/edit?usp=sharing)

***Components:***
- [ ] UI
- [ ] Step 1 React Component - connected to redux
- [ ] Step 1 React localization
- [ ] Step 1 Preview UI
- [ ] Step 1 Preview Component - connected to redux
- [ ] Step 1 Preview localization

**Comment by nicolsonaitken** [comment]
The first step in creating a Job Poster is by entering basic job information; Job Poster Timetable, Job Details and, Work Details followed by a Preview and confirmation. 

Link to Wireframe(s):

- [ ]  [Create a Job Poster](https://talent-cloud.pagecloud.com/create-a-job-poster)
- [ ]  [Preview Job Poster](https://talent-cloud.pagecloud.com/looking-good)

Note: Content to be finalized by @mattejackson.
