### ISSUE TITLE
Manager - Progress Tracker React component

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#958]
# Description
Built to be reusable.

- [ ] Progress Tracker (top right of wireframe) should have 3 states for each step (Incomplete, Active, Complete). This page is the first step and should update that "circle".
- [ ] Steps should start as Incomplete, Update to Active while on the page and Complete if validation passes and page is saved.
- [ ] The steps for this progress Tracker should NOT be links. We don't want people skipping ahead at this point. This should be improved in the future, see #947.

Testing:

- [ ] Storybook story.
- [ ] Jest snapshot testing.

Link to wireframe: https://xd.adobe.com/view/8662c71a-8638-4f03-7c9c-14abc4c92df3-f053/
